### ISSUE TITLE
Custom build is failing

### ISSUE THREAD

**Issue by StoyanDimitrov** [ZeptoJS/Zepto.js#8]
The output
```
prompt> npm run-script dist

> zepto@1.2.0 dist path-here\zepto.js
> coffee make dist

dist/zepto.js: 48.5 KiB
path-here\zepto.js\make:171
    compressor = uglify.Compressor();
                        ^

TypeError: uglify.Compressor is not a function
    at minify (path-here\zepto.js\make:171:25)
    at Function.target.minify (path-here\zepto.js\make:92:14)
    at Object.target.(anonymous function) [as minify] (path-here\zepto.js\node_modules\shelljs\make.js:28:26)
    at Function.target.dist (path-here\zepto.js\make:56:12)
    at Object.target.(anonymous function) [as dist] (path-here\zepto.js\node_modules\shelljs\make.js:28:26)
    at path-here\zepto.js\node_modules\shelljs\make.js:38:20
    at Array.forEach (<anonymous>:null:null)
    at Timeout._onTimeout (path-here\zepto.js\node_modules\shelljs\make.js:36:10)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zepto@1.2.0 dist: `coffee make dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zepto@1.2.0 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
Win10, node 11.2

Reverting to the version of uglify from the original repo fixes the issue.

**Comment by DanielRuf** [comment]
I will check this.

**Comment by DanielRuf** [comment]
It's a breaking change in uglify-js >= 3.

It works with `"uglify-js": "^2.6.0"` which should be the preferred solution to prevent breaking changes (SemVer).

**Comment by DanielRuf** [comment]
![grafik](https://user-images.githubusercontent.com/827205/72045844-61d56380-32b7-11ea-98be-1f6ee9836c87.png)

I will provide a patch and fix the SemVer selector.

**Comment by DanielRuf** [comment]
This was caused by https://github.com/ZeptoJS/Zepto.js/commit/5260bd6436c033e5aae6512781e0e5c4b61989ce

I recommend doing a `yarn && yarn upgrade-interactive --latest` to update the entry in the package.json file.

Or `ncu` / `npm-check-updates`.
